kafka:
  monitor:
    zookeeper: 192.168.6.166:2181,192.168.6.167:2181

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: kafka-monitor
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  aop:
    proxy-target-class: true
  jmx:
    default-domain: ${spring.application.name}
  freemarker:
    allow-session-override: true
    check-template-location: true
    suffix: .ftl
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    settings:
      auto_import: common/spring.ftl as spring
      number_format: '0.##'
  datasource:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db_server:127.0.0.1:3306}/${db_name:kafka}?allowPublicKeyRetrieval=true&serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: zhangningpegasus
    druid:
      # 配置初始化大小
      initialSize: 1
      # 配置连接池中最小可用连接的个数
      minIdle: 200
      # 配置连接池中最大可用连接的个数
      maxActive: 1000
      # 配置获取连接等待超时的时间, 单位是毫秒
      maxWait: 60000
      # 配置间隔多久才进行一次检测, 检测需要关闭的空闲连接, 单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间, 单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      validationQueryTimeout: 60000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache, 并且指定每个连接上PSCache的大小.分库分表较多的数据库，建议配置为false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

mybatis-plus:
  mapper-locations: classpath:com.pegasus.kafka.mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    ## 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file: classpath:logback.xml

